variable "engine" {}
variable "engine_version" {}
variable "num_cache_nodes" {}
variable "node_type" {}
variable "env" {}
variable "tags" {}
variable "subnet_ids" {}
variable "vpc_id" {}
variable "allow_subnets" {}